namespace: "uat"
replicas: 1

techStack: "nodejs"

image:
  repositoryPrefix: "ghcr.io/pagopa/interop-probing-core/interop-be-probing-api"
  imagePullPolicy: Always
  tag: $IMAGE_TAG_PLACEHOLDER
  digest: $IMAGE_DIGEST_PLACEHOLDER

deployment:
  env:
    LOG_LEVEL: "info"

resources:
  requests:
    cpu: "1"
    memory: "2Gi"
  limits:
    cpu: "1"
    memory: "2Gi"
