name: "interop-be-probing-response-updater"

roleArn: ""

service:
  create: false

configMap:
  SQS_ENDPOINT_POLL_RESULT_QUEUE: "https://sqs.eu-central-1.amazonaws.com/010158505074/eservice_polling_result_queue"
  INTEROP_PROBING_RESPONSE_UPDATER_NAME: "interop-be-probing-response-updater"

deployment:
  envFromConfigmaps:
    AWS_REGION: "interop-be-probing-common.AWS_REGION"  
    CONSUMER_POLLING_TIMEOUT_IN_SECONDS: "interop-be-probing-common.CONSUMER_POLLING_TIMEOUT_IN_SECONDS"  
    API_OPERATIONS_BASEURL: "interop-be-probing-common.API_OPERATIONS_BASEURL"

autoscaling:
    horizontal:
      create: true 
      config:
        minReplicas: 1
        maxReplicas: 10
        targetCPUUtilizationPercentage: 80
