deployment:
  name: interop-be-probing-statistics-api
  replicas: 1
  image:
    repository: ghcr.io/pagopa/interop-probing-core/interop-be-probing-statistics-api
    tag: develop
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi
  env:
    - name: HOST
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-statistics-api
          key: HOST
    - name: PORT
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-statistics-api
          key: PORT
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-common
          key: LOG_LEVEL
    - name: GRAPH_MAX_MONTHS
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-statistics-api
          key: GRAPH_MAX_MONTHS
    - name: GRAPH_PERFORMANCE_TOLERANCE
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-statistics-api
          key: GRAPH_PERFORMANCE_TOLERANCE

configMap:
  TIMESTREAM_DATABASE: "interop_probing_telemetry"
  TIMESTREAM_TABLE: "probing_telemetry"
  CORS_ORIGIN_ALLOWED: "*"
  INTEROP_PROBING_STATISTICS_APP_NAME: "interop-be-probing-statistics-api"
  GRAPH_PERFORMANCE_TOLERANCE: "2"
  GRAPH_FAILURE_TOLERANCE: "4"
  GRAPH_MAX_MONTHS: "3"
  HOST: "0.0.0.0"
  PORT: "8080"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

service:
  name: interop-be-probing-statistics-api
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP

ingress:
  enabled: true
  name: interop-be-probing-statistics-api
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: interop-probing-alb-dev
  rules:
    - host: ""
      http:
        paths:
          - path: /telemetryData
            pathType: Prefix
            backend:
              service:
                name: interop-be-probing-statistics-api
                port:
                  number: 80
