apiVersion: v1
kind: ConfigMap
metadata:
  name: common-probing-store
  namespace: dev
data:
  DB_HOST: interop-probing-operational-database-dev.cluster-caudw4yuwazj.eu-central-1.rds.amazonaws.com
  DB_NAME: interop_probing_operational
  DB_PORT: "5432"
  
