apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: interop-be-probing-telemetry-writer
spec:
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: interop-be-probing-telemetry-writer
  targetCPUUtilizationPercentage: 80