deployment:
  name: interop-be-probing-eservice-registry-caller
  replicas: 1
  image:
    repository: ghcr.io/pagopa/interop-probing-core/interop-be-probing-caller
    tag: develop
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi
  env:
    - name: CONSUMER_POLLING_TIMEOUT_IN_SECONDS
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-common
          key: CONSUMER_POLLING_TIMEOUT_IN_SECONDS
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-common
          key: LOG_LEVEL
    - name: AWS_REGION
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-common
          key: AWS_REGION
    - name: SQS_ENDPOINT_POLL_QUEUE
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-eservice-registry-caller
          key: SQS_ENDPOINT_POLL_QUEUE
    - name: SQS_ENDPOINT_POLL_RESULT_QUEUE
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-eservice-registry-caller
          key: SQS_ENDPOINT_POLL_RESULT_QUEUE
    - name: SQS_ENDPOINT_TELEMETRY_RESULT_QUEUE
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-eservice-registry-caller
          key: SQS_ENDPOINT_TELEMETRY_RESULT_QUEUE
    - name: JWT_PAYLOAD_EXPIRE_TIME_IN_SEC
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-eservice-registry-caller
          key: JWT_PAYLOAD_EXPIRE_TIME_IN_SEC
    - name: JWT_PAYLOAD_ISSUER
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-eservice-registry-caller
          key: JWT_PAYLOAD_ISSUER
    - name: JWT_PAYLOAD_SUBJECT
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-eservice-registry-caller
          key: JWT_PAYLOAD_SUBJECT
    - name: JWT_PAYLOAD_KID_KMS
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-eservice-registry-caller
          key: JWT_PAYLOAD_KID_KMS

configMap:
  SQS_ENDPOINT_POLL_QUEUE: "https://sqs.eu-central-1.amazonaws.com/774300547186/eservice_polling_queue"
  SQS_ENDPOINT_POLL_RESULT_QUEUE: "https://sqs.eu-central-1.amazonaws.com/774300547186/eservice_polling_result_queue"
  SQS_ENDPOINT_TELEMETRY_RESULT_QUEUE: "https://sqs.eu-central-1.amazonaws.com/774300547186/eservice_telemetry_result_queue"
  JWT_PAYLOAD_EXPIRE_TIME_IN_SEC: "60"
  JWT_PAYLOAD_ISSUER: "monitoring.dev.interop.pagopa.it"
  JWT_PAYLOAD_SUBJECT: "monitoring.dev.interop.pagopa.it"
  JWT_PAYLOAD_KID_KMS: "f9af55d7-6e12-4d11-9f7d-bc1bfd6870f8"
  INTEROP_PROBING_CALLER_NAME: "interop-be-probing-caller"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80