name: "interop-be-probing-eservice-registry-caller"

serviceAccount:
  roleArn: ""

service:
  create: false

configMap:
  SQS_ENDPOINT_POLL_QUEUE: "https://sqs.eu-central-1.amazonaws.com/774300547186/eservice_polling_queue"
  SQS_ENDPOINT_POLL_RESULT_QUEUE: "https://sqs.eu-central-1.amazonaws.com/774300547186/eservice_polling_result_queue"
  SQS_ENDPOINT_TELEMETRY_RESULT_QUEUE: "https://sqs.eu-central-1.amazonaws.com/774300547186/eservice_telemetry_result_queue"
  JWT_PAYLOAD_EXPIRE_TIME_IN_SEC: "60"
  JWT_PAYLOAD_ISSUER: "monitoring.dev.interop.pagopa.it"
  JWT_PAYLOAD_SUBJECT: "monitoring.dev.interop.pagopa.it"
  JWT_PAYLOAD_KID_KMS: "f9af55d7-6e12-4d11-9f7d-bc1bfd6870f8"
  INTEROP_PROBING_CALLER_NAME: "interop-be-probing-caller"

deployment:
  envFromConfigmaps:
    CONSUMER_POLLING_TIMEOUT_IN_SECONDS: "interop-be-probing-common.CONSUMER_POLLING_TIMEOUT_IN_SECONDS"
    AWS_REGION: "interop-be-probing-common.AWS_REGION"
    SQS_ENDPOINT_POLL_QUEUE: "interop-be-probing-eservice-registry-caller.SQS_ENDPOINT_POLL_QUEUE"
    SQS_ENDPOINT_POLL_RESULT_QUEUE: "interop-be-probing-eservice-registry-caller.SQS_ENDPOINT_POLL_RESULT_QUEUE"
    SQS_ENDPOINT_TELEMETRY_RESULT_QUEUE: "interop-be-probing-eservice-registry-caller.SQS_ENDPOINT_TELEMETRY_RESULT_QUEUE"
    JWT_PAYLOAD_EXPIRE_TIME_IN_SEC: "interop-be-probing-eservice-registry-caller.JWT_PAYLOAD_EXPIRE_TIME_IN_SEC"
    JWT_PAYLOAD_ISSUER: "interop-be-probing-eservice-registry-caller.JWT_PAYLOAD_ISSUER"
    JWT_PAYLOAD_SUBJECT: "interop-be-probing-eservice-registry-caller.JWT_PAYLOAD_SUBJECT"
    JWT_PAYLOAD_KID_KMS: "interop-be-probing-eservice-registry-caller.JWT_PAYLOAD_KID_KMS"

autoscaling:
    horizontal:
      create: true 
      config:
        minReplicas: 1
        maxReplicas: 10
        targetCPUUtilizationPercentage: 80