name: "interop-be-probing-statistics-api"

roleArn: ""

service:
  create: true
  name: interop-be-probing-statistics-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP

configMap:
  TIMESTREAM_DATABASE: "interop_probing_telemetry"
  TIMESTREAM_TABLE: "probing_telemetry"
  CORS_ORIGIN_ALLOWED: "*"
  INTEROP_PROBING_STATISTICS_APP_NAME: "interop-be-probing-statistics-api"
  GRAPH_PERFORMANCE_TOLERANCE: "2"
  GRAPH_FAILURE_TOLERANCE: "4"
  GRAPH_MAX_MONTHS: "3"

deployment:
  env:
    HOST: "0.0.0.0"
    PORT: "8080"
  envFromConfigmaps:
    GRAPH_MAX_MONTHS: "interop-be-probing-statistics-api.GRAPH_MAX_MONTHS"
    GRAPH_PERFORMANCE_TOLERANCE: "interop-be-probing-statistics-api.GRAPH_PERFORMANCE_TOLERANCE"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: true
  name: interop-be-probing-statistics-api
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: interop-probing-alb-uat
  rules:
    - host: ""
      http:
        paths:
          - path: /telemetryData
            pathType: Prefix
            backend:
              service:
                name: interop-be-probing-statistics-api
                port:
                  number: 80
