name: "probing-api"
roleArn: ""

service:
  name: interop-be-probing-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP

configMap:
  HOST: "0.0.0.0"
  PORT: "8080"
  CORS_ORIGIN_ALLOWED: "*"
  TOLERANCE_MULTIPLIER_IN_MINUTES: "3"
  INTEROP_PROBING_API_APP_NAME: "interop-be-probing-api"

deployment:
  name: interop-be-probing-api
  replicas: 1
  envFromConfigmaps:
    HOST: "interop-be-probing-api.HOST"
    PORT: "interop-be-probing-api.PORT"
    LOG_LEVEL: "interop-be-probing-common.LOG_LEVEL"
    AWS_REGION: "interop-be-probing-common.AWS_REGION"
    API_OPERATIONS_BASEURL: "interop-be-probing-common.API_OPERATIONS_BASEURL"
    CORS_ORIGIN_ALLOWED: "interop-be-probing-api.CORS_ORIGIN_ALLOWED"
    TOLERANCE_MULTIPLIER_IN_MINUTES: "interop-be-probing-api.TOLERANCE_MULTIPLIER_IN_MINUTES"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: true
  name: interop-be-probing-api
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: interop-probing-alb-dev
  rules:
    - host: ""
      http:
        paths:
          - path: /eservices
            pathType: Prefix
            backend:
              service:
                name: interop-be-probing-api
                port:
                  number: 80
          - path: /producers
            pathType: Prefix
            backend:
              service:
                name: interop-be-probing-api
                port:
                  number: 80