deployment:
  name: interop-be-probing-api
  replicas: 1
  image:
    repository: ghcr.io/pagopa/interop-probing-core/interop-be-probing-api
    tag: develop
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi
  env:
    - name: HOST
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-api
          key: HOST
    - name: PORT
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-api
          key: PORT
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-common
          key: LOG_LEVEL
    - name: AWS_REGION
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-common
          key: AWS_REGION
    - name: API_OPERATIONS_BASEURL
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-common
          key: API_OPERATIONS_BASEURL
    - name: CORS_ORIGIN_ALLOWED
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-api
          key: CORS_ORIGIN_ALLOWED
    - name: TOLERANCE_MULTIPLIER_IN_MINUTES
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-api
          key: TOLERANCE_MULTIPLIER_IN_MINUTES

configMap:
  HOST: "0.0.0.0"
  PORT: "8080"
  CORS_ORIGIN_ALLOWED: "*"
  TOLERANCE_MULTIPLIER_IN_MINUTES: "3"
  INTEROP_PROBING_API_APP_NAME: "interop-be-probing-api"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

service:
  name: interop-be-probing-api
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP

ingress:
  enabled: true
  name: interop-be-probing-api
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: interop-probing-alb-dev
  rules:
    - host: ""
      http:
        paths:
          - path: /eservices
            pathType: Prefix
            backend:
              service:
                name: interop-be-probing-api
                port:
                  number: 80
          - path: /producers
            pathType: Prefix
            backend:
              service:
                name: interop-be-probing-api
                port:
                  number: 80