deployment:
  name: interop-be-probing-telemetry-writer
  replicas: 1
  envFromConfigmaps:
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-common
          key: LOG_LEVEL
    - name: AWS_REGION
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-common
          key: AWS_REGION
    - name: CONSUMER_POLLING_TIMEOUT_IN_SECONDS
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-common
          key: CONSUMER_POLLING_TIMEOUT_IN_SECONDS
    - name: SQS_ENDPOINT_TELEMETRY_RESULT_QUEUE
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-telemetry-writer
          key: SQS_ENDPOINT_TELEMETRY_RESULT_QUEUE

configMap:
  SQS_ENDPOINT_TELEMETRY_RESULT_QUEUE: "https://sqs.eu-central-1.amazonaws.com/010158505074/eservice_telemetry_result_queue"
  TIMESTREAM_DATABASE: "interop_probing_telemetry"
  TIMESTREAM_TABLE: "probing_telemetry"
  TIMESTREAM_RETRIES: "10"
  INTEROP_PROBING_TELEMETRY_WRITER_NAME: "interop-be-probing-telemetry-writer"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80