deployment:
  name: interop-be-probing-scheduler
  replicas: 1
  image:
    repository: ghcr.io/pagopa/interop-probing-core/interop-be-probing-scheduler
    tag: develop
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi
  env:
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-common
          key: LOG_LEVEL
    - name: AWS_REGION
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-common
          key: AWS_REGION
    - name: API_OPERATIONS_BASEURL
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-common
          key: API_OPERATIONS_BASEURL
    - name: SQS_ENDPOINT_POLL_QUEUE
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-scheduler
          key: SQS_ENDPOINT_POLL_QUEUE
    - name: SCHEDULER_LIMIT
      valueFrom:
        configMapKeyRef:
          name: interop-be-probing-scheduler
          key: SCHEDULER_LIMIT

configMap:
  SQS_ENDPOINT_POLL_QUEUE: "https://sqs.eu-central-1.amazonaws.com/774300547186/eservice_polling_queue"
  SCHEDULER_CRON_EXPRESSION: "0 * * * * *"
  SCHEDULER_LIMIT: "10"
  THREADPOOL_MAX_POOL_SIZE: "7"
  INTEROP_PROBING_SCHEDULER_NAME: "interop-be-probing-scheduler"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
